/**
 * SolarEstimator Component
 * Tool for calculating rooftop solar potential. Provides technical sizing, 
 * financial ROI analysis (LKR), and environmental impact reports.
 */
import React, { useState } from 'react';
import Layout from '../components/Layout';
import { solarApi } from '../services/api';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import {
  BarChart,
  Bar,
  AreaChart,
  Area,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  ResponsiveContainer,
  Cell
} from 'recharts';

const SolarEstimator = () => {
  const [area, setArea] = useState('');
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState(null);
  const [error, setError] = useState('');
  const [location, setLocation] = useState({ lat: null, lon: null });
  const [gettingLocation, setGettingLocation] = useState(false);

  // Request user's geolocation to provide coordinates to the NREL solar API
  const fetchLocation = () => {
    if (!navigator.geolocation) {
      setError('Geolocation is not supported by your browser.');
      return;
    }
    setGettingLocation(true);
    navigator.geolocation.getCurrentPosition(
      (pos) => {
        setLocation({ lat: pos.coords.latitude, lon: pos.coords.longitude });
        setGettingLocation(false);
      },
      (err) => {
        setError('Could not get location. Using Sri Lanka average.');
        setGettingLocation(false);
      }
    );
  };

  const handleCalculate = async (e) => {
    e.preventDefault();
    if (!area || area <= 0) {
      setError('Please enter a valid rooftop area.');
      return;
    }

    setLoading(true);
    setError('');
    try {
      const response = await solarApi.estimate({
        rooftopArea: parseFloat(area),
        lat: location.lat,
        lon: location.lon
      });
      setResult(response.data);
    } catch (err) {
      setError('Failed to calculate. Please try again.');
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  // Logic to generate and download a technical PDF report using jsPDF
  const handleDownloadPDF = () => {
    if (!result) return;

    const doc = new jsPDF();

    // Header - Title & Design
    doc.setFillColor(20, 184, 166);
    doc.rect(0, 0, 210, 40, 'F');

    doc.setTextColor(255, 255, 255);
    doc.setFontSize(24);
    doc.setFont('helvetica', 'bold');
    doc.text('Solar Potential Report', 15, 20);

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(`Generated by Flux Energy Audit | ${new Date().toLocaleDateString()}`, 15, 30);

    // Section 1: Technical Overview
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.text('1. Technical Analysis', 15, 55);

    const technicalData = [
      ['Metric', 'Value'],
      ['Rooftop Area', `${result.input.rooftopArea} sqft`],
      ['System Capacity', `${result.technical.systemCapacityKWp} kWp`],
      ['Estimated Panels', `${result.technical.numberOfPanels} (550W High-Efficiency)`],
      ['Avg. Monthly Units', `${result.technical.monthlyGenerationUnits} kWh`],
      ['Annual Generation', `${result.technical.yearlyGenerationUnits} kWh`]
    ];

    autoTable(doc, {
      head: [technicalData[0]],
      body: technicalData.slice(1),
      startY: 62,
      styles: { fontSize: 10, cellPadding: 5 },
      headStyles: { fillColor: [20, 184, 166], textColor: 255 }
    });

    // Section 2: Financial ROI
    const finalY = doc.lastAutoTable.finalY + 15;
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.text('2. Financial ROI (Sri Lankan context)', 15, finalY);

    const financialData = [
      ['Metric', 'Amount (LKR)'],
      ['Total Estimated Investment', `LKR ${result.financial.estimatedCostLKR.toLocaleString()}`],
      ['Estimated Monthly Savings', `LKR ${result.financial.monthlySavingsLKR.toLocaleString()}`],
      ['Annual Estimated Savings', `LKR ${result.financial.yearlySavingsLKR.toLocaleString()}`],
      ['Payback Period', `${result.financial.paybackPeriod.years} Years, ${result.financial.paybackPeriod.months} Months`]
    ];

    autoTable(doc, {
      head: [financialData[0]],
      body: financialData.slice(1),
      startY: finalY + 7,
      styles: { fontSize: 10, cellPadding: 5 },
      headStyles: { fillColor: [59, 130, 246], textColor: 255 }
    });

    // Section 3: Environmental Impact
    const envY = doc.lastAutoTable.finalY + 15;
    doc.setTextColor(34, 197, 94);
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.text('3. Environmental Impact', 15, envY);

    doc.setTextColor(0, 0, 0);
    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    doc.text([
      `By installing this ${result.technical.systemCapacityKWp}kW solar system, you are reducing your`,
      `carbon footprint by approximately ${result.environmental.carbonOffsetTonnesPerYearUnrounded} Metric Tons of CO2 per year.`,
      `This is equivalent to planting roughly ${Math.round(result.environmental.carbonOffsetTonnesPerYearUnrounded * 15)} trees annually.`
    ], 15, envY + 10);

    // Footer - Verification
    const pageHeight = doc.internal.pageSize.height;
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    const verificationText = result.technical.isRealTimeData ?
      'Verified with NREL weather station data for the provided coordinates.' :
      'Calculated using Sri Lankan regional solar averages.';
    doc.text(`${verificationText} Flux Energy Audit - 2026`, 15, pageHeight - 15);

    // Save PDF
    doc.save(`Flux_Solar_Report_${result.input.rooftopArea}sqft.pdf`);
  };

  const SummaryCard = ({ title, value, unit, icon, colorClass }) => (
    <div className="card-premium flex flex-col items-center text-center">
      <div className={`p-4 rounded-full ${colorClass} bg-opacity-10 mb-4`}>
        <span className={`text-2xl ${colorClass.replace('bg-', 'text-')}`}>{icon}</span>
      </div>
      <h3 className="text-secondary-text text-sm font-medium mb-1">{title}</h3>
      <div className="text-2xl font-bold text-primary-text">
        {value} <span className="text-sm font-normal text-secondary-text">{unit}</span>
      </div>
    </div>
  );

  return (
    <Layout>
      <div className="max-w-6xl mx-auto px-4 py-12">
        <div className="text-center mb-12">
          <h1 className="text-4xl md:text-5xl font-extrabold mb-4">
            Solar <span className="text-gradient">Potential Estimator</span>
          </h1>
          <p className="text-secondary-text max-w-2xl mx-auto">
            Discover the solar energy potential of your home. Enter your available rooftop area to estimate system capacity, costs, and savings tailored for Sri Lanka.
          </p>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
          {/* Input Section */}
          <div className="lg:col-span-1">
            <div className="card-premium">
              <h2 className="text-xl font-bold mb-6">Enter Details</h2>
              <form onSubmit={handleCalculate}>
                <div className="mb-6">
                  <label className="block text-sm font-medium text-secondary-text mb-2 flex justify-between items-center">
                    Rooftop Area (sqft)
                    <button
                      type="button"
                      onClick={fetchLocation}
                      className={`text-xs font-bold uppercase tracking-tight flex items-center gap-1 ${location.lat ? 'text-green-600' : 'text-teal-600 hover:text-teal-800'}`}
                    >
                      <svg xmlns="http://www.w3.org/2000/svg" className="h-3 w-3" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17.657 16.657L13.414 20.9a1.998 1.998 0 01-2.827 0l-4.244-4.243a8 8 0 1111.314 0z" />
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 11a3 3 0 11-6 0 3 3 0 016 0z" />
                      </svg>
                      {gettingLocation ? 'Locating...' : location.lat ? 'Location Shared' : 'Enable High Precision'}
                    </button>
                  </label>
                  <div className="relative">
                    <input
                      type="number"
                      value={area}
                      onChange={(e) => setArea(e.target.value)}
                      placeholder="e.g., 500"
                      className="w-full px-4 py-3 rounded-xl border border-gray-200 focus:outline-none focus:ring-2 focus:ring-teal-500 focus:border-transparent transition-all"
                    />
                    <span className="absolute right-4 top-1/2 -translate-y-1/2 text-gray-400">sqft</span>
                  </div>
                  {location.lat && (
                    <p className="text-[10px] text-green-600 mt-2 font-medium flex items-center gap-1">
                      <span className="w-1.5 h-1.5 bg-green-500 rounded-full animate-pulse"></span>
                      Precision Mode: Using real weather data for your coordinates.
                    </p>
                  )}
                </div>

                <button
                  type="submit"
                  disabled={loading}
                  className="btn-primary w-full flex justify-center items-center gap-2"
                >
                  {loading ? (
                    'Calculating...'
                  ) : (
                    <>
                      <span>Generate Estimate</span>
                      <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                        <path fillRule="evenodd" d="M10.293 3.293a1 1 0 011.414 0l6 6a1 1 0 010 1.414l-6 6a1 1 0 01-1.414-1.414L14.586 11H3a1 1 0 110-2h11.586l-4.293-4.293a1 1 0 010-1.414z" clipRule="evenodd" />
                      </svg>
                    </>
                  )}
                </button>
              </form>

              {error && (
                <div className="mt-4 p-3 bg-red-50 text-red-600 rounded-xl text-sm border border-red-100">
                  {error}
                </div>
              )}

              <div className="mt-8 p-4 bg-teal-50 rounded-2xl border border-teal-100">
                <h4 className="font-bold text-teal-800 text-sm mb-2 flex items-center gap-2">
                  <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                  </svg>
                  How it works
                </h4>
                <ul className="text-[11px] text-teal-700 space-y-1.5 leading-tight">
                  <li>• Estimates use 550W high-efficiency panels.</li>
                  <li>• Analysis is localized for Sri Lankan energy tariffs.</li>
                  <li>• "Enable High Precision" uses NREL weather data.</li>
                </ul>
              </div>
            </div>
          </div>

          {/* Results Section */}
          <div className="lg:col-span-2">
            {!result ? (
              <div className="card-premium h-full min-h-[400px] flex flex-col items-center justify-center text-center opacity-60">
                <div className="w-20 h-20 bg-gray-100 rounded-full flex items-center justify-center mb-6">
                  <svg xmlns="http://www.w3.org/2000/svg" className="h-10 w-10 text-gray-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z" />
                  </svg>
                </div>
                <h3 className="text-xl font-bold mb-2">No Estimate Generated</h3>
                <p className="max-w-xs">Enter your rooftop area on the left to see your personalized solar forecast.</p>
              </div>
            ) : (
              <div className="space-y-8 animate-in fade-in duration-700">
                {/* Summary Grid */}
                <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
                  <SummaryCard
                    title="System Size"
                    value={result.technical.systemCapacityKWp}
                    unit="kWp"
                    colorClass="bg-teal-500"
                    icon="⚡"
                  />
                  <SummaryCard
                    title="Estimated Panels"
                    value={result.technical.numberOfPanels}
                    unit="Panels"
                    colorClass="bg-blue-500"
                    icon="⬜"
                  />
                  <SummaryCard
                    title="Payback Period"
                    value={`${result.financial.paybackPeriod.years}y ${result.financial.paybackPeriod.months}m`}
                    unit=""
                    colorClass="bg-orange-500"
                    icon="⏳"
                  />
                  <SummaryCard
                    title="Carbon Offset"
                    value={result.environmental.carbonOffsetTonnesPerYearUnrounded}
                    unit="Tons/yr"
                    colorClass="bg-green-500"
                    icon="🌱"
                  />
                </div>

                {result.technical.isRealTimeData && (
                  <div className="card-premium bg-gradient-to-br from-slate-50 to-teal-50 border-teal-100 flex flex-col gap-6">
                    <div className="flex flex-col md:flex-row justify-between items-start md:items-center border-b border-teal-100/50 pb-4">
                      <div className="flex items-center gap-3">
                        <div className="w-10 h-10 bg-white rounded-xl shadow-sm flex items-center justify-center text-teal-600">
                          <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17.657 16.657L13.414 20.9a1.998 1.998 0 01-2.827 0l-4.244-4.243a8 8 0 1111.314 0z" />
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 11a3 3 0 11-6 0 3 3 0 016 0z" />
                          </svg>
                        </div>
                        <div>
                          <h3 className="font-bold text-slate-800">
                            {result.technical.extraMetrics?.locationName || 'Regional Solar Insights'}
                          </h3>
                          <p className="text-[10px] text-teal-600 font-bold uppercase tracking-widest">
                            Lat: {result.input.lat?.toFixed(4)} | Lon: {result.input.lon?.toFixed(4)}
                          </p>
                        </div>
                      </div>
                      {result.technical.extraMetrics?.stationInfo && (
                        <div className="mt-4 md:mt-0 text-right">
                          <span className="text-[10px] text-secondary-text font-bold uppercase block tracking-wider">Source Station</span>
                          <span className="text-sm font-bold text-slate-700">{result.technical.extraMetrics.stationInfo.city} ({result.technical.extraMetrics.stationInfo.distance} km away)</span>
                        </div>
                      )}
                    </div>

                    <div className="grid grid-cols-2 lg:grid-cols-4 gap-6">
                      <div className="p-4 bg-white rounded-2xl border border-teal-100/50 shadow-sm">
                        <p className="text-secondary-text text-[10px] font-bold uppercase mb-2">Peak Month</p>
                        <div className="flex items-center justify-between">
                          <span className="font-bold text-slate-700">
                            {['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'][
                              result.technical.monthlyBreakdown.indexOf(Math.max(...result.technical.monthlyBreakdown))
                            ]}
                          </span>
                          <span className="text-green-600 font-bold text-[8px] bg-green-50 px-1.5 py-0.5 rounded-lg">High Radiation</span>
                        </div>
                      </div>

                      <div className="p-4 bg-white rounded-2xl border border-teal-100/50 shadow-sm">
                        <p className="text-secondary-text text-[10px] font-bold uppercase mb-2">Annual Irradiance</p>
                        <div className="flex items-center justify-between">
                          <span className="font-bold text-slate-700">{result.technical.extraMetrics?.annualSolarRadiation || '---'}</span>
                          <span className="text-xs font-normal text-secondary-text">kWh/m²/day</span>
                        </div>
                      </div>

                      <div className="p-4 bg-white rounded-2xl border border-teal-100/50 shadow-sm">
                        <p className="text-secondary-text text-[10px] font-bold uppercase mb-2">Capacity Factor</p>
                        <div className="flex items-center justify-between">
                          <span className="font-bold text-slate-700">{result.technical.extraMetrics?.capacityFactor || '---'}%</span>
                          <span className="text-teal-600 font-bold text-[8px] bg-teal-50 px-1.5 py-0.5 rounded-lg">High</span>
                        </div>
                      </div>

                      <div className="p-4 bg-white rounded-2xl border border-teal-100/50 shadow-sm">
                        <p className="text-secondary-text text-[10px] font-bold uppercase mb-2">Env. Reliability</p>
                        <div className="flex items-center gap-2">
                          <div className="flex gap-1">
                            {[1, 2, 3, 4, 5].map(i => (
                              <div key={i} className={`w-3 h-1.5 rounded-full ${i <= 5 ? 'bg-emerald-500' : 'bg-gray-200'}`}></div>
                            ))}
                          </div>
                          <span className="text-[10px] font-bold text-emerald-700 uppercase">100%</span>
                        </div>
                      </div>
                    </div>

                    <div className="p-5 border border-teal-100/50 bg-white/30 rounded-[24px]">
                      <div className="flex flex-col md:flex-row gap-8">
                        <div className="flex-1 space-y-4">
                          <div className="flex justify-between items-center text-xs font-medium border-b border-teal-100/30 pb-2">
                            <span className="text-secondary-text">Station Quality</span>
                            <span className="text-slate-800">Class 1 Solar Data</span>
                          </div>
                          <div className="flex justify-between items-center text-xs font-medium border-b border-teal-100/30 pb-2">
                            <span className="text-secondary-text">Avg. Seasonal Variance</span>
                            <span className="text-slate-800">±12.4%</span>
                          </div>
                          <div className="flex justify-between items-center text-xs font-medium">
                            <span className="text-secondary-text">System Reliability</span>
                            <span className="text-slate-800 font-bold">99.9% On-Grid</span>
                          </div>
                        </div>
                        <div className="flex-1 bg-teal-600 text-white p-4 rounded-2xl flex flex-col justify-center">
                          <p className="text-[10px] font-bold uppercase opacity-80 mb-2">Highest Monthly Harvest</p>
                          <div className="flex items-end gap-3">
                            <span className="text-3xl font-extrabold">{Math.max(...result.technical.monthlyBreakdown).toLocaleString()}</span>
                            <span className="text-xs font-medium mb-1.5 opacity-90 uppercase">units (kWh)</span>
                          </div>
                          <p className="text-[10px] opacity-70 mt-3 flex items-center gap-1 leading-tight">
                            Predicted for {['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'][
                              result.technical.monthlyBreakdown.indexOf(Math.max(...result.technical.monthlyBreakdown))
                            ]} based on {result.technical.extraMetrics?.annualSolarRadiation} irradiance index.
                          </p>
                        </div>
                      </div>
                    </div>
                  </div>
                )}

                {/* Financial Deep Dive */}
                <div className="card-premium">
                  <div className="flex flex-col md:flex-row justify-between items-start md:items-center mb-8">
                    <div>
                      <h2 className="text-2xl font-bold flex items-center gap-2">
                        Financial Analysis
                        {result.technical.isRealTimeData && (
                          <span className="px-2 py-1 bg-green-100 text-green-700 text-[10px] rounded-md font-bold uppercase tracking-wider">
                            Verified Data
                          </span>
                        )}
                      </h2>
                      <p className="text-secondary-text text-sm">Estimated investment and ROI</p>
                    </div>
                    <div className="mt-4 md:mt-0 px-4 py-2 bg-green-50 text-green-700 rounded-full text-sm font-bold border border-green-100 flex items-center gap-2">
                      <span className="w-2 h-2 bg-green-500 rounded-full animate-pulse"></span>
                      LKR {result.financial.monthlySavingsLKR.toLocaleString()} Monthly Savings
                    </div>
                  </div>

                  <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                    <div className="space-y-6">
                      <div className="flex justify-between items-center p-4 bg-gray-50 rounded-2xl">
                        <div>
                          <span className="text-secondary-text text-xs uppercase tracking-wider font-bold">Total Investment</span>
                          <div className="text-2xl font-bold text-teal-600">LKR {result.financial.estimatedCostLKR.toLocaleString()}</div>
                        </div>
                        <div className="text-right">
                          <span className="text-secondary-text text-xs">Capacity: {result.technical.systemCapacityKWp}kW</span>
                        </div>
                      </div>

                      <div className="space-y-4">
                        <div className="flex justify-between items-center text-sm">
                          <span className="text-secondary-text">Avg. Units per Month</span>
                          <span className="font-bold">{result.technical.monthlyGenerationUnits} kWh</span>
                        </div>
                        <div className="w-full bg-gray-100 h-2 rounded-full overflow-hidden">
                          <div className="bg-teal-500 h-full rounded-full" style={{ width: '100%' }}></div>
                        </div>

                        <div className="flex justify-between items-center text-sm">
                          <span className="text-secondary-text">Annual Energy (units)</span>
                          <span className="font-bold">{result.technical.yearlyGenerationUnits.toLocaleString()} kWh</span>
                        </div>
                        <div className="w-full bg-gray-100 h-2 rounded-full overflow-hidden">
                          <div className="bg-blue-500 h-full rounded-full" style={{ width: '85%' }}></div>
                        </div>

                        <div className="flex justify-between items-center text-sm pt-4 border-top border-gray-100">
                          <span className="text-secondary-text">Annual Savings</span>
                          <span className="font-bold text-green-600">LKR {result.financial.yearlySavingsLKR.toLocaleString()}</span>
                        </div>
                      </div>
                    </div>

                    <div className="h-[250px]">
                      <ResponsiveContainer width="100%" height="100%">
                        <BarChart data={result.technical.monthlyBreakdown ?
                          result.technical.monthlyBreakdown.map((val, idx) => ({
                            name: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'][idx],
                            units: val
                          })) :
                          [
                            { name: 'Monthly Savings', value: result.financial.monthlySavingsLKR },
                            { name: 'Installation / 10', value: result.financial.estimatedCostLKR / 120 },
                          ]
                        }>
                          <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#f1f5f9" />
                          <XAxis dataKey="name" axisLine={false} tickLine={false} tick={{ fontSize: 10, fill: '#64748b' }} />
                          <Tooltip
                            contentStyle={{ borderRadius: '16px', border: 'none', boxShadow: '0 10px 15px -3px rgb(0 0 0 / 0.1)' }}
                            cursor={{ fill: '#f8fafc' }}
                          />
                          <Bar dataKey={result.technical.monthlyBreakdown ? "units" : "value"} radius={[6, 6, 0, 0]} barSize={30}>
                            {result.technical.monthlyBreakdown ?
                              result.technical.monthlyBreakdown.map((entry, index) => (
                                <Cell key={`cell-${index}`} fill={index === 0 ? '#14b8a6' : '#55C48B'} />
                              )) :
                              <>
                                <Cell fill="#14b8a6" />
                                <Cell fill="#cbd5e1" />
                              </>
                            }
                          </Bar>
                        </BarChart>
                      </ResponsiveContainer>
                      <p className="text-center text-xs text-secondary-text mt-2">
                        {result.technical.monthlyBreakdown ? 'Seasonal Energy Generation (kWh)' : 'Savings vs Amortized Cost'}
                      </p>
                    </div>
                  </div>
                </div>

                {/* Irradiance Variance Chart - Scientific View */}
                {result.technical.isRealTimeData && result.technical.extraMetrics?.monthlySolarRadiation && (
                  <div className="card-premium animate-in slide-in-from-bottom-4 duration-1000">
                    <div className="flex justify-between items-center mb-6">
                      <div>
                        <h3 className="font-bold text-slate-800">Irradiance Variance (Scientific)</h3>
                        <p className="text-[10px] text-teal-600 font-bold uppercase tracking-widest">Seasonal Solar Radiation Profile</p>
                      </div>
                      <div className="text-right">
                        <span className="text-xs font-bold text-slate-400">Station-Specific Irradiance Index</span>
                      </div>
                    </div>

                    <div className="h-[200px]">
                      <ResponsiveContainer width="100%" height="100%">
                        <AreaChart data={result.technical.extraMetrics.monthlySolarRadiation.map((val, idx) => ({
                          name: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'][idx],
                          radiation: parseFloat(val)
                        }))}>
                          <defs>
                            <linearGradient id="colorRadiation" x1="0" y1="0" x2="0" y2="1">
                              <stop offset="5%" stopColor="#14b8a6" stopOpacity={0.3} />
                              <stop offset="95%" stopColor="#14b8a6" stopOpacity={0} />
                            </linearGradient>
                          </defs>
                          <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#f1f5f9" />
                          <XAxis dataKey="name" axisLine={false} tickLine={false} tick={{ fontSize: 10, fill: '#64748b' }} />
                          <YAxis axisLine={false} tickLine={false} tick={{ fontSize: 10, fill: '#64748b' }} />
                          <Tooltip
                            contentStyle={{ borderRadius: '16px', border: 'none', boxShadow: '0 10px 15px -3px rgb(0 0 0 / 0.1)' }}
                          />
                          <Area type="monotone" dataKey="radiation" stroke="#14b8a6" strokeWidth={3} fillOpacity={1} fill="url(#colorRadiation)" />
                        </AreaChart>
                      </ResponsiveContainer>
                      <p className="text-center text-[10px] text-secondary-text mt-3">
                        Energy Flux Density (kWh/m²/day) over 12 months.
                      </p>
                    </div>
                  </div>
                )}

                <div className="p-6 bg-slate-900 rounded-[32px] text-white flex flex-col md:flex-row items-center justify-between gap-6">
                  <div className="flex items-center gap-4 text-center md:text-left">
                    <div className="text-4xl">🚀</div>
                    <div>
                      <h4 className="font-bold text-lg text-teal-400">Ready to go green?</h4>
                      <p className="text-slate-400 text-sm">Convert your rooftop into an income generator.</p>
                    </div>
                  </div>
                  <button
                    onClick={handleDownloadPDF}
                    className="px-8 py-3 bg-white text-slate-900 font-bold rounded-full hover:bg-teal-400 transition-colors"
                  >
                    Download Detailed PDF
                  </button>
                </div>
              </div>
            )}
          </div>
        </div>
      </div>
    </Layout>
  );
};

export default SolarEstimator;
